@Rebus.API_HostAddress = https://localhost:7246


GET {{Rebus.API_HostAddress}}/api/users/games/accesses
###
GET {{Rebus.API_HostAddress}}/api/users/4/games/accesses

###
GET {{Rebus.API_HostAddress}}/api/users

###
GET {{Rebus.API_HostAddress}}/api/games






###
DELETE {{Rebus.API_HostAddress}}/api/users/3

###
DELETE {{Rebus.API_HostAddress}}/api/games/3

###
Post {{Rebus.API_HostAddress}}/api/users
Content-Type: application/json

{ 
  "UserName" : "AccessUser",
  "IsLoggedIn" : false,
  "Email" : "Test@gmail.com"
}

###
Post {{Rebus.API_HostAddress}}/api/games
Content-Type: application/json

{ 
  "GameName" : "AccessGame",
  "AccessCode" : "0001"
}
###

POST {{Rebus.API_HostAddress}}/api/users/23/games/4/access
Content-Type: application/json

{
  "AccessTime" : "2019-01-06"
}


###
PATCH {{Rebus.API_HostAddress}}/api/users/1
Content-Type: application/json

{
  "city" : "Oslo"
}

