@Rebus.API_HostAddress = https://localhost:7246


GET {{Rebus.API_HostAddress}}/api/users/games/accesses

###
GET {{Rebus.API_HostAddress}}/api/users

###
DELETE {{Rebus.API_HostAddress}}/api/users/5

###
Post {{Rebus.API_HostAddress}}/api/users
Content-Type: application/json

{ 
  "UserName" : "Post",
  "IsLoggedIn" : false,
  "Email" : "Test@gmail.com"
}

###
GET https://localhost:7246/api/users/3

###

PATCH {{Rebus.API_HostAddress}}/api/users/1
Content-Type: application/json

{
  "city" : "Oslo"
}

###

POST {{Rebus.API_HostAddress}}/api/users/1/games/1/accesses
Content-Type: application/json

{
  "AccessTime" : "2019-01-06"
}

###
